/**
 * Represents a single demonstrable Next.js pattern change between versions.
 *
 * @example
 * {
 *   id: "async-request-apis",
 *   title: "Async Request APIs",
 *   version: 15,
 *   category: "data-fetching-caching",
 *   isBreakingChange: true,
 *   migrationImpact: "HIGH",
 *   blogPostLink: "https://nextjs.org/blog/next-15#async-request-apis",
 *   beforeAfterSummary: "Before: headers() returns immediately. After: await headers() required.",
 *   description: "In Next.js 15, request APIs like headers(), cookies(), and params became async...",
 *   whyItMatters: "This breaking change affects all applications using request APIs...",
 *   codeSnippetBefore: "const headersList = headers();",
 *   codeSnippetAfter: "const headersList = await headers();",
 *   keyChanges: ["All request APIs now async", "Requires await keyword", "Codemod available"],
 *   availableInOtherVersion: true,
 *   relatedExampleId: "async-params-v16"
 * }
 */
export interface PatternExample {
  /** Unique identifier in kebab-case */
  id: string;

  /** Display title (max 60 chars) */
  title: string;

  /** Next.js version (15 or 16) */
  version: 15 | 16;

  /** Category reference (must match canonical category ID) */
  category: string;

  /** Breaking change flag - true if requires code changes */
  isBreakingChange: boolean;

  /** Migration complexity: HIGH, MEDIUM, or LOW */
  migrationImpact: "HIGH" | "MEDIUM" | "LOW";

  /** Official blog post URL */
  blogPostLink: string;

  /** One-sentence comparison (max 120 chars) */
  beforeAfterSummary: string;

  /** Explanation of change (200-400 chars) */
  description: string;

  /** Rationale for change (300-500 chars) */
  whyItMatters: string;

  /** Code example showing old pattern (valid TypeScript/JSX, max 50 lines) */
  codeSnippetBefore?: string;

  /** Code example showing new pattern (valid TypeScript/JSX, max 50 lines) */
  codeSnippetAfter: string;

  /** Pre-rendered highlighted HTML for "before" code (generated by Shiki at build time) */
  highlightedHTMLBefore?: string;

  /** Pre-rendered highlighted HTML for "after" code (generated by Shiki at build time) */
  highlightedHTMLAfter?: string;

  /** Bullet points of specific changes (2-5 items, each max 100 chars) */
  keyChanges: string[];

  /** Cross-version availability flag */
  availableInOtherVersion: boolean;

  /** ID of equivalent example in other version (if availableInOtherVersion=true) */
  relatedExampleId?: string;
}
